import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useActiveProfile, useWalletLogin } from "@lens-protocol/react";
import { useSigner } from "wagmi";

const Home: NextPage = () => {
  const { login, isPending } = useWalletLogin();
  const { data: signer, isLoading: isSignerLoading } = useSigner();
  const { data: profile, loading: profileLoading } = useActiveProfile();

  return (
    <div className={styles.container}>
      <Head>
        <title>Embrace</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed z-0 h-16 w-full flex flex-row items-center p-3 bg-slate-200 ">
        <div className="basis-1/3">
          <div className="md:hidden h-14 w-14 bg-slate-50 rounded-full"></div>
        </div>
        <div className="basis-1/3 text-center">search bar</div>

        <div className="basis-1/3 text-end mr-4"> account </div>
      </div>

      {/* Main content including side nav */}
      <div className="flex w-full h-screen">
        <div className="hidden md:flex flex-col w-44 p-3 bg-slate-500 z-10  text-center">
          <div className="h-16 w-16 mx-auto p-3 bg-slate-50 rounded-full mb-8"></div>
          <div className="py-4 border-t-2 opacity-70"></div>
          <div className="h-16 w-16 mx-auto p-3 bg-slate-50 rounded-full mb-4"></div>
          <div className="h-16 w-16 mx-auto p-3 bg-slate-50 rounded-full mb-4"></div>

          <div className="grow"></div>

          <div className="h-12 w-12 mx-auto p-3 bg-slate-50 rounded-full mb-4"></div>
        </div>

        <div className="overflow-scroll mt-16">
          <div className="p-3 bg-blue-200 ">
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>

            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>

            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
          </div>
        </div>
      </div>

      {/* Mobile Navigation*/}
      <div className="md:hidden flex flex-row fixed bottom-0 z-0 h-16 w-full items-center text-center p-3 bg-slate-100">
        <div className="basis-1/4"> Option 1 </div>
        <div className="basis-1/4"> Option 2 </div>
        <div className="basis-1/4"> Option 3 </div>
        <div className="basis-1/4"> Option 4 </div>
      </div>

      {/* Footer - if required */}
      <div className="hidden md:flex flex-row fixed bottom-0 z-0 h-8 w-full  items-center p-3 bg-slate-100">
        <div className="grow text-center"> footer </div>
      </div>
    </div>
  );
};

export default Home;
