import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useActiveProfile, useWalletLogin } from "@lens-protocol/react";
import { useSigner } from "wagmi";

const Home: NextPage = () => {
  const { login, isPending } = useWalletLogin();
  const { data: signer, isLoading: isSignerLoading } = useSigner();
  const { data: profile, loading: profileLoading } = useActiveProfile();

  return (
    <div className={styles.container}>
      <Head>
        <title>Embrace</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Work on getting the search bar and account in a single flex div? */}
      <div className="fixed z-0 h-16 w-full flex items-center p-3 bg-slate-200">
        <div className="grow text-center"> search bar </div>
      </div>

      <div className="fixed right-0 z-0 h-16 w-36 flex items-center p-3 bg-slate-200">
        <div className="grow text-center"> account </div>
      </div>

      {/* Main content including side nav */}
      <div className="w-full h-screen flex">
        <div className="w-44 p-3 bg-slate-500 z-10 flex flex-col text-center">
          <div className="h-12 w-12 mx-auto p-3 bg-slate-50 rounded-full mb-8"></div>
          <div className="py-4 border-t-2 opacity-70"></div>
          <div className="h-12 w-12 mx-auto p-3 bg-slate-50 rounded-full mb-4"></div>
          <div className="h-12 w-12 mx-auto p-3 bg-slate-50 rounded-full mb-4"></div>

          <div className="grow"></div>

          <div className="h-12 w-12 mx-auto p-3 bg-slate-50 rounded-full mb-4"></div>
        </div>

        <div className="overflow-scroll mt-16">
          <div className="p-3 bg-blue-200 ">
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>

            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>

            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
            <p>
              {" "}
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio,
              praesentium quibusdam non, tenetur voluptas, animi iusto modi unde
              voluptatem dolorem facere ea est quod dolor sunt odit molestias
              perferendis sit. Lorem ipsum dolor sit amet consectetur,
              adipisicing elit. Optio, praesentium quibusdam non, tenetur
              voluptas, animi iusto modi unde voluptatem dolorem facere ea est
              quod dolor sunt odit molestias perferendis sit. Lorem ipsum dolor
              sit amet consectetur, adipisicing elit. Optio, praesentium
              quibusdam non, tenetur voluptas, animi iusto modi unde voluptatem
              dolorem facere ea est quod dolor sunt odit
            </p>
          </div>
        </div>
      </div>

      {/* Footer - if required */}
      <div className="fixed bottom-0 z-0 h-8 w-full flex items-center p-3 bg-slate-100">
        <div className="grow text-center"> footer </div>
      </div>
    </div>
  );
};

export default Home;
