import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useActiveProfile, useWalletLogin } from "@lens-protocol/react";
import { useSigner } from "wagmi";

const Home: NextPage = () => {
  const { login, isPending } = useWalletLogin();
  const { data: signer, isLoading: isSignerLoading } = useSigner();
  const { data: profile, loading: profileLoading } = useActiveProfile();

  const onLoginClick = async () => {
    if (!signer) return;

    await login(signer);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Embrace</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {profile && (
          <>
            <p>
              Welcome <b>@{profile.handle}</b>
            </p>
          </>
        )}
        {/* {!profile && !profileLoading && signer && ( */}
        <button disabled={isPending} onClick={onLoginClick}>
          Log in
        </button>
        {/* )} */}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
