/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface CommunityTableMethodsInterface extends utils.Interface {
  functions: {
    "createKeyValueTable()": FunctionFragment;
    "createMemberTable()": FunctionFragment;
    "insertMember(uint256)": FunctionFragment;
    "keyValueTable()": FunctionFragment;
    "memberTable()": FunctionFragment;
    "setPrefix(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createKeyValueTable"
      | "createMemberTable"
      | "insertMember"
      | "keyValueTable"
      | "memberTable"
      | "setPrefix"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createKeyValueTable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMemberTable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "insertMember",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "keyValueTable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "memberTable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPrefix",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createKeyValueTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMemberTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keyValueTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrefix", data: BytesLike): Result;

  events: {};
}

export interface CommunityTableMethods extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CommunityTableMethodsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createKeyValueTable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMemberTable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    insertMember(
      _memberId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    keyValueTable(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

    memberTable(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

    setPrefix(
      _tablePrefix: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createKeyValueTable(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMemberTable(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  insertMember(
    _memberId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  keyValueTable(
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

  memberTable(
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

  setPrefix(
    _tablePrefix: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createKeyValueTable(overrides?: CallOverrides): Promise<void>;

    createMemberTable(overrides?: CallOverrides): Promise<void>;

    insertMember(
      _memberId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    keyValueTable(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

    memberTable(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

    setPrefix(
      _tablePrefix: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    createKeyValueTable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMemberTable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    insertMember(
      _memberId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    keyValueTable(overrides?: CallOverrides): Promise<BigNumber>;

    memberTable(overrides?: CallOverrides): Promise<BigNumber>;

    setPrefix(
      _tablePrefix: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createKeyValueTable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMemberTable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    insertMember(
      _memberId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    keyValueTable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    memberTable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setPrefix(
      _tablePrefix: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
