/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace EmbraceApps {
  export type AppStruct = {
    id: PromiseOrValue<BigNumberish>;
    code: PromiseOrValue<string>;
    contractAddress: PromiseOrValue<string>;
    enabled: PromiseOrValue<boolean>;
    metadata: PromiseOrValue<string>;
  };

  export type AppStructOutput = [BigNumber, string, string, boolean, string] & {
    id: BigNumber;
    code: string;
    contractAddress: string;
    enabled: boolean;
    metadata: string;
  };
}

export interface EmbraceAppsInterface extends utils.Interface {
  functions: {
    "apps(uint256)": FunctionFragment;
    "codeToIndex(bytes32)": FunctionFragment;
    "createApp(string,address,string,bool)": FunctionFragment;
    "getAppByCode(string)": FunctionFragment;
    "getAppByIndex(uint256)": FunctionFragment;
    "getApps()": FunctionFragment;
    "owner()": FunctionFragment;
    "setAppContractAddress(string,address)": FunctionFragment;
    "updateMetadata(uint256,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "apps"
      | "codeToIndex"
      | "createApp"
      | "getAppByCode"
      | "getAppByIndex"
      | "getApps"
      | "owner"
      | "setAppContractAddress"
      | "updateMetadata"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "apps",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "codeToIndex",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "createApp",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppByCode",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppByIndex",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "getApps", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAppContractAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "apps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "codeToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createApp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAppByCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getApps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAppContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;

  events: {};
}

export interface EmbraceApps extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EmbraceAppsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    apps(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, boolean, string] & {
        id: BigNumber;
        code: string;
        contractAddress: string;
        enabled: boolean;
        metadata: string;
      }
    >;

    codeToIndex(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createApp(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      _metadata: PromiseOrValue<string>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAppByCode(
      _code: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[EmbraceApps.AppStructOutput]>;

    getAppByIndex(
      _appId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[EmbraceApps.AppStructOutput]>;

    getApps(
      overrides?: CallOverrides
    ): Promise<[EmbraceApps.AppStructOutput[]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setAppContractAddress(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMetadata(
      _appId: PromiseOrValue<BigNumberish>,
      _newMetadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  apps(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, boolean, string] & {
      id: BigNumber;
      code: string;
      contractAddress: string;
      enabled: boolean;
      metadata: string;
    }
  >;

  codeToIndex(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createApp(
    _code: PromiseOrValue<string>,
    _contractAddress: PromiseOrValue<string>,
    _metadata: PromiseOrValue<string>,
    _enabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAppByCode(
    _code: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<EmbraceApps.AppStructOutput>;

  getAppByIndex(
    _appId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<EmbraceApps.AppStructOutput>;

  getApps(overrides?: CallOverrides): Promise<EmbraceApps.AppStructOutput[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  setAppContractAddress(
    _code: PromiseOrValue<string>,
    _contractAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMetadata(
    _appId: PromiseOrValue<BigNumberish>,
    _newMetadata: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    apps(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, boolean, string] & {
        id: BigNumber;
        code: string;
        contractAddress: string;
        enabled: boolean;
        metadata: string;
      }
    >;

    codeToIndex(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createApp(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      _metadata: PromiseOrValue<string>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAppByCode(
      _code: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<EmbraceApps.AppStructOutput>;

    getAppByIndex(
      _appId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<EmbraceApps.AppStructOutput>;

    getApps(overrides?: CallOverrides): Promise<EmbraceApps.AppStructOutput[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    setAppContractAddress(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMetadata(
      _appId: PromiseOrValue<BigNumberish>,
      _newMetadata: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<EmbraceApps.AppStructOutput>;
  };

  filters: {};

  estimateGas: {
    apps(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    codeToIndex(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createApp(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      _metadata: PromiseOrValue<string>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAppByCode(
      _code: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAppByIndex(
      _appId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getApps(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setAppContractAddress(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMetadata(
      _appId: PromiseOrValue<BigNumberish>,
      _newMetadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    apps(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    codeToIndex(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createApp(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      _metadata: PromiseOrValue<string>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAppByCode(
      _code: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAppByIndex(
      _appId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getApps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAppContractAddress(
      _code: PromiseOrValue<string>,
      _contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMetadata(
      _appId: PromiseOrValue<BigNumberish>,
      _newMetadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
