/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmbraceAccounts } from "./EmbraceAccounts";
export type { EmbraceApps } from "./EmbraceApps";
export type { EmbraceSpaces } from "./EmbraceSpaces";
