/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export type CommunityMetaDataStruct = {
  handle: PromiseOrValue<string>;
  name: PromiseOrValue<string>;
  description: PromiseOrValue<string>;
  image: PromiseOrValue<string>;
};

export type CommunityMetaDataStructOutput = [string, string, string, string] & {
  handle: string;
  name: string;
  description: string;
  image: string;
};

export interface TablelandCommunitiesInterface extends utils.Interface {
  functions: {
    "_insertCommunity(uint256,(string,string,string,string))": FunctionFragment;
    "communitiesTable()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "_insertCommunity" | "communitiesTable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_insertCommunity",
    values: [PromiseOrValue<BigNumberish>, CommunityMetaDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "communitiesTable",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_insertCommunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "communitiesTable",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TablelandCommunities extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TablelandCommunitiesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _insertCommunity(
      newCommunityId: PromiseOrValue<BigNumberish>,
      _communityMetaData: CommunityMetaDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    communitiesTable(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;
  };

  _insertCommunity(
    newCommunityId: PromiseOrValue<BigNumberish>,
    _communityMetaData: CommunityMetaDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  communitiesTable(
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;

  callStatic: {
    _insertCommunity(
      newCommunityId: PromiseOrValue<BigNumberish>,
      _communityMetaData: CommunityMetaDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    communitiesTable(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { id: BigNumber; name: string }>;
  };

  filters: {};

  estimateGas: {
    _insertCommunity(
      newCommunityId: PromiseOrValue<BigNumberish>,
      _communityMetaData: CommunityMetaDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    communitiesTable(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _insertCommunity(
      newCommunityId: PromiseOrValue<BigNumberish>,
      _communityMetaData: CommunityMetaDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    communitiesTable(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
