/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as appCreationsCollectionSol from "./AppCreationsCollection";

export type { appCreationsCollectionSol };
export type { AppCreations } from "./AppCreations";
